import comments
import json

response = comments.get_comments_simple()

# prof Turk choice
# extracting them specifically
result = []
for i, comment in enumerate(response["items"]):
    try:
        text = comment["snippet"]["topLevelComment"]["snippet"]["textOriginal"]
        date = comment["snippet"]["topLevelComment"]["snippet"]["publishedAt"]
        result += [[text, date]]
    except:
        print(f"Structure Different for Comment {i}")

# recursive for loop that is more general (not based on structure)
print(result)
# Also, extract date from the comments as well.
# {
#     "kind": "youtube#commentThreadListResponse",
#     "etag": "arhtZ26_pii67ZQ6-fE8YelHbXQ",
#     "nextPageToken": "QURTSl9pMzEzUWE2SHZtTFdiSExjQ1hTWlM0SXlyUXo3emRvcjFXUUFDVjlnNW9aN2NBQUxRem9xSGZ2bnZGRTZ4d3JrbnN6WmtiU2oxQQ==",
#     "pageInfo": {"totalResults": 20, "resultsPerPage": 20},
#     "items": [
#         {
#             "kind": "youtube#commentThread",
#             "etag": "-IHeb4iWwntDUBE3VjJ9cfpM9jc",
#             "id": "Ugwye5aOxwvHdAmzpzB4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "QhwBQG6KMHGEMH86LUgDT6cl7j8",
#                     "id": "Ugwye5aOxwvHdAmzpzB4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": 'at <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=25m17s">25:17</a> when he says (row1)^T * x=0. This is wrong. Row1 is 1xn and x is nx1. Row1*x=0. row1^T is nx1 and you can&#39;t multiply a nx1 vector by x another nx1 vector.',
#                         "textOriginal": "at 25:17 when he says (row1)^T * x=0. This is wrong. Row1 is 1xn and x is nx1. Row1*x=0. row1^T is nx1 and you can't multiply a nx1 vector by x another nx1 vector.",
#                         "authorDisplayName": "Mina Gobran",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/29C8JIQsXHn0Htt571K8Nn8iDZRpO6FYlCFIpTFCDoqMPw3V1Onc0bCAzAywpN8IPlzr3vo3Fw=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCZ2kX__QJSqP5JgpYWTjo-Q",
#                         "authorChannelId": {"value": "UCZ2kX__QJSqP5JgpYWTjo-Q"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-11-29T04:05:56Z",
#                         "updatedAt": "2022-11-29T04:05:56Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 1,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "IWfNVKgbK7JX404IG9mHvEAqjCg",
#             "id": "UgyOOTmmOkcnHf4nJpl4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "Towu0CMdYvF9JODofEbOQZEuGYA",
#                     "id": "UgyOOTmmOkcnHf4nJpl4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": '<a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=00h00m00s">00:00:00</a> to <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=00h02m50s">00:02:50</a> : Introduction<br><a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=00h02m51s">00:02:51</a> to <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=00h13m45s">00:13:45</a> : What is Orthogonality?<br><a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=00h13m50s">00:13:50</a> to <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=20h49m00s">20:49:00</a> : What is Orthogonality for Subspaces?<br><a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=00h20m50s">00:20:50</a> to <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=26h00m00s">26:00:00</a> : Why RS(A) ⊥ NS(A)?<br><a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=26h01m00s">26:01:00</a> to <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=34h00m00s">34:00:00</a> : What is Orthogonal complement?<br><a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=39h45m00s">39:45:00</a> to End      : Properties of A^T.A ?',
#                         "textOriginal": "00:00:00 to 00:02:50 : Introduction\n00:02:51 to 00:13:45 : What is Orthogonality?\n00:13:50 to 20:49:00 : What is Orthogonality for Subspaces?\n00:20:50 to 26:00:00 : Why RS(A) ⊥ NS(A)?\n26:01:00 to 34:00:00 : What is Orthogonal complement?\n39:45:00 to End      : Properties of A^T.A ?",
#                         "authorDisplayName": "Palash Nandi",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJU9aCkTVnljY6YKkj4n4A8l39hncbu0j731ZFFe=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UC_NtBkAIdPQZIlwWALKKnxA",
#                         "authorChannelId": {"value": "UC_NtBkAIdPQZIlwWALKKnxA"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 1,
#                         "publishedAt": "2022-10-17T09:20:34Z",
#                         "updatedAt": "2022-10-17T09:20:34Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "xovcShGnRn8JJlv4gyNgacolBhw",
#             "id": "UgwZ_g3vhbi8MoR_QRB4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "NqqqQk7YNpkSEPdxZecraTmnGWQ",
#                     "id": "UgwZ_g3vhbi8MoR_QRB4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "East or West, Prof Strang is the best!",
#                         "textOriginal": "East or West, Prof Strang is the best!",
#                         "authorDisplayName": "Jackson Sunny",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJVXOE9m9BoVTTRCMd732mUZm2FaqjNepbgS7k8F4Q=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UC4jMed0gGfHFQN0bMfpOC6g",
#                         "authorChannelId": {"value": "UC4jMed0gGfHFQN0bMfpOC6g"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-10-16T09:43:10Z",
#                         "updatedAt": "2022-10-16T09:43:10Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "XkwZ7JJmZFaox7taSEj8lukyBX0",
#             "id": "UgxCVHOu16BanT_XVhp4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "xLBeK4MC2kKxaUONGMTeYNCFeo8",
#                     "id": "UgxCVHOu16BanT_XVhp4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "thank a lot",
#                         "textOriginal": "thank a lot",
#                         "authorDisplayName": "山田 林",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJVGWqRtgMUxqd6jdaZT3Zdk3sGhBojSBLSOBhUmt38kbA=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCzGXKG9ExeQdTghad9-_OWA",
#                         "authorChannelId": {"value": "UCzGXKG9ExeQdTghad9-_OWA"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 1,
#                         "publishedAt": "2022-09-24T06:25:37Z",
#                         "updatedAt": "2022-09-24T06:25:37Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "odaryMUHgPietL2lGDOGt91XOo4",
#             "id": "Ugy5lH3QrCFvuhBNusd4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "73e5gp8vvaK2e3oytnbLaTp-bU4",
#                     "id": "Ugy5lH3QrCFvuhBNusd4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "Thank you prof I&#39;m writing a exam tomorrow morning",
#                         "textOriginal": "Thank you prof I'm writing a exam tomorrow morning",
#                         "authorDisplayName": "Wandile Investment",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJUc11Tc_rRNztW7ooHRqqlxTCNosEAsS-i7LGXD=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCeG05dSqLOks3fbK4Ra3-Mg",
#                         "authorChannelId": {"value": "UCeG05dSqLOks3fbK4Ra3-Mg"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 1,
#                         "publishedAt": "2022-09-07T05:14:10Z",
#                         "updatedAt": "2022-09-07T05:14:10Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "9mR7_ehdnMV-g3-BJVoH47AEU3M",
#             "id": "UgytS8IBHg2N7tko4Sp4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "R3q7IFgQH5G-ifZL3VaICf5UbHY",
#                     "id": "UgytS8IBHg2N7tko4Sp4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "Beautiful lecture and amazing lecturer !!!",
#                         "textOriginal": "Beautiful lecture and amazing lecturer !!!",
#                         "authorDisplayName": "Tan Phan",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJXWC7PADUHz4jNsQqld338kXlbwV_blcQs2oNvmCA=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UC9OXnzAfsG6_Tc_WYXxq6rw",
#                         "authorChannelId": {"value": "UC9OXnzAfsG6_Tc_WYXxq6rw"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-07-31T07:11:22Z",
#                         "updatedAt": "2022-07-31T07:11:22Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "N1vfmJE71-7h04xe-NElVmWqniU",
#             "id": "UgxRRUuQaLYqMdABewl4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "xGaHrKXmcaqGRE_0YOhDvkvF9c4",
#                     "id": "UgxRRUuQaLYqMdABewl4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": '<a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=41m32s">41:32</a> recap point for A.t * Ax = A.t * b',
#                         "textOriginal": "41:32 recap point for A.t * Ax = A.t * b",
#                         "authorDisplayName": "JockyItch",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/yKBcCOhPvTADTais7SP9AmqlpzrsDDMd9tMTQYx21m8MJkDMkL0TMfxZKIIpXDYFSz5G9WlndA=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCcTKff6V6YekvBE1pn6kQfQ",
#                         "authorChannelId": {"value": "UCcTKff6V6YekvBE1pn6kQfQ"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-07-22T03:37:16Z",
#                         "updatedAt": "2022-07-22T03:37:16Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "J8O6v0IDn603lXn_KMZueLyexWk",
#             "id": "UgwmgY4J2egRcXKJOLh4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "W169q61AZ_afzIZIgBFGx54AVlE",
#                     "id": "UgwmgY4J2egRcXKJOLh4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "Amazing, thk u MIT and Prof. Gilbert Strang.",
#                         "textOriginal": "Amazing, thk u MIT and Prof. Gilbert Strang.",
#                         "authorDisplayName": "Antonio Said Webbe Sales",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/2KncThkJarxn_OIKeTuvnDdIp6fZAxhOyQNquG9-yakCzcPoSaolGxlRDMOF-MdHfvvjm2SGZg=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCKIFrohE4_TKvxf4FYPj-Rw",
#                         "authorChannelId": {"value": "UCKIFrohE4_TKvxf4FYPj-Rw"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-06-15T14:39:48Z",
#                         "updatedAt": "2022-06-15T14:39:48Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "6P1IWNoF32m5qKGuL-dtavz1UhM",
#             "id": "UgyUBuVCdeKwRexhaZB4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "l3obG-nebcz6_Pk3Ux5xhfm2qkw",
#                     "id": "UgyUBuVCdeKwRexhaZB4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": '@ <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=21m55s">21:55</a> Jerry Seinfeld',
#                         "textOriginal": "@ 21:55 Jerry Seinfeld",
#                         "authorDisplayName": "John Gilroy",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJWxqSIiJKQX8C2HfoVL8NcNrTwf1eXJzKHEMA=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCJQ11h55mxGEDkC34ZkI5YA",
#                         "authorChannelId": {"value": "UCJQ11h55mxGEDkC34ZkI5YA"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-05-04T18:40:46Z",
#                         "updatedAt": "2022-05-04T18:40:46Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "M8V83kw90bCLudco2Fg3cZj7_3A",
#             "id": "UgxGsWGgsHdeFfO4n854AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "WKDElqA3fqOiDZ3W0kd7nT3XabQ",
#                     "id": "UgxGsWGgsHdeFfO4n854AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "Really enjoying this series! Thank you professor Strang and MIT. This is absolute service to humanity!",
#                         "textOriginal": "Really enjoying this series! Thank you professor Strang and MIT. This is absolute service to humanity!",
#                         "authorDisplayName": "Ninad Gandhi",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJUYSwOI4fHCoCe9RlvonylXcNc-iePz_9q4RJk5FxukVexJWHshkAeuhmd0VkR4=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCZ5nUB9mCWYWCDE7ykPdfSA",
#                         "authorChannelId": {"value": "UCZ5nUB9mCWYWCDE7ykPdfSA"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-05-03T15:09:14Z",
#                         "updatedAt": "2022-05-03T15:09:14Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "MiTBvAX8DphoRlULcnrQi6vXZTI",
#             "id": "UgzEyBcbzvOtvHQJZyF4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "Bd8e2LQ6SKtBzk46YLxiRBr2Ukc",
#                     "id": "UgzEyBcbzvOtvHQJZyF4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "In many linear algebra courses that I have seen, the student is simply told about the various relationships between the fundamental subspaces. But in this course these ideas are convincingly yet accessibly presented. This is very important because it allows students to really understand such key ideas of linear algebra to the point where they become intuitive, instead of simply memorizing properties and formulas. Another great lecture by professor Strang!",
#                         "textOriginal": "In many linear algebra courses that I have seen, the student is simply told about the various relationships between the fundamental subspaces. But in this course these ideas are convincingly yet accessibly presented. This is very important because it allows students to really understand such key ideas of linear algebra to the point where they become intuitive, instead of simply memorizing properties and formulas. Another great lecture by professor Strang!",
#                         "authorDisplayName": "Professor Fernando Hartwig",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/n6Bx7joTMHGhfhyCx_0s7PscStOpvtSZvuZDGvHeHdFWQpDtBG7sdNGiAqtVD1aERV9It15_-v4=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCI5c_YnIFST5xpWUxQ5BaLg",
#                         "authorChannelId": {"value": "UCI5c_YnIFST5xpWUxQ5BaLg"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 1,
#                         "publishedAt": "2022-04-28T02:44:57Z",
#                         "updatedAt": "2022-04-28T02:44:57Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "u13Sjsa9pGticjbUuCAhnThkvn8",
#             "id": "Ugx8Oi5SQpUdp8D3L7R4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "xUce-Qx4zjN941KIIcGocbZR22Y",
#                     "id": "Ugx8Oi5SQpUdp8D3L7R4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "Brilliant leacture",
#                         "textOriginal": "Brilliant leacture",
#                         "authorDisplayName": "pawan kumar",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJVN7xut42qn04sx0mkwH2SxzXtQ9cwwwaZnFWnJ3w=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCjed4GHu9sE6-Wqa_CoK5IA",
#                         "authorChannelId": {"value": "UCjed4GHu9sE6-Wqa_CoK5IA"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-03-21T16:29:21Z",
#                         "updatedAt": "2022-03-21T16:29:21Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "Wc_JEjIdWUDoHVMVtYztSQ6FrlY",
#             "id": "UgzH0KqxM3iC_0ONofp4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "g2LbJX88DsvwEWxBsj7WFjzGMnE",
#                     "id": "UgzH0KqxM3iC_0ONofp4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": 'At <a href="https://www.youtube.com/watch?v=YzZUIYRCE38&amp;t=36m22s">36:22</a>, it is fascinating how he got a bit into the orbital mechanics, saying there are 6 unknowns (which is rightly known at the State vector, which is a 6 by 1 matrix with Position (x,y,z) and velocities (xdot, ydot, zdot)).',
#                         "textOriginal": "At 36:22, it is fascinating how he got a bit into the orbital mechanics, saying there are 6 unknowns (which is rightly known at the State vector, which is a 6 by 1 matrix with Position (x,y,z) and velocities (xdot, ydot, zdot)).",
#                         "authorDisplayName": "Adarsh Agrawal",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJW801_u6FA-75KUe2epNTzef6-TNBAJkGmbSPUhiHw=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCP76wEJbZ_JA_-XrXkRfOew",
#                         "authorChannelId": {"value": "UCP76wEJbZ_JA_-XrXkRfOew"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 1,
#                         "publishedAt": "2022-02-19T20:19:59Z",
#                         "updatedAt": "2022-02-19T20:19:59Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "OOIE6PWGTkvMVKBDaBhkzDHPPfc",
#             "id": "UgxBNj4WcfNrxiWQJht4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "CtVa_jTUubrKtMXyLt77Ee9yFg0",
#                     "id": "UgxBNj4WcfNrxiWQJht4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "Cameraman would have become Pro in Linear Algebra by absorbing such a high level of teaching.",
#                         "textOriginal": "Cameraman would have become Pro in Linear Algebra by absorbing such a high level of teaching.",
#                         "authorDisplayName": "Best Bites",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/mhzZszmewBxOWHZmUU1HGZMTrAwU4AsjBonIFvSh2LNZMgRXmvfhlK-arofjUD_wiiN5miJW=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCqlg80LvZuCa52PtWzlky_Q",
#                         "authorChannelId": {"value": "UCqlg80LvZuCa52PtWzlky_Q"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-02-01T17:37:11Z",
#                         "updatedAt": "2022-02-01T17:37:11Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "9HNHwkdVzXVeArzqN-5IarZDkd4",
#             "id": "UgxsJHzRhlQPdwT2vER4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "HxsLgnM-sGucNGOyx7c60Fn8juQ",
#                     "id": "UgxsJHzRhlQPdwT2vER4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": 'At <a href="https://youtu.be/YzZUIYRCE38?t=615">https://youtu.be/YzZUIYRCE38?t=615</a>, Professor Strang applies FOIL to vectors.  I&#39;m not clear on why you can do that.',
#                         "textOriginal": "At https://youtu.be/YzZUIYRCE38?t=615, Professor Strang applies FOIL to vectors.  I'm not clear on why you can do that.",
#                         "authorDisplayName": "Bass Maiasa",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJV3OB76J-kUqamV0c9y66bDlhaelcMK2NbpZ7IF=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCAHr_f1x8JHZ_24md1ncr_A",
#                         "authorChannelId": {"value": "UCAHr_f1x8JHZ_24md1ncr_A"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-01-30T05:14:05Z",
#                         "updatedAt": "2022-01-30T05:14:05Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 1,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "0MaQFTz7pgOl59t-c72njkhAah0",
#             "id": "Ugyt06yx7KgdBcZPQn94AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "cYqLB-sg13WSceoN5v6LU1ZtGLY",
#                     "id": "Ugyt06yx7KgdBcZPQn94AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "why exactly is the null space of (A transpose )(A) = to the null space of A ?",
#                         "textOriginal": "why exactly is the null space of (A transpose )(A) = to the null space of A ?",
#                         "authorDisplayName": "Bipasha T",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJV3wz7LaG7mC3UgJluTFAv0vDh7MO2i7XELQ5QCQRE=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCnF9AdYpBEahtepDJSNmpUw",
#                         "authorChannelId": {"value": "UCnF9AdYpBEahtepDJSNmpUw"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-01-17T07:03:52Z",
#                         "updatedAt": "2022-01-17T07:03:52Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "Rs6KdBUkn6DXmBzNYT2YeDgWKAY",
#             "id": "UgxgEFI5QddEkFem21t4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "LBZ98uOZXa0v2ksWXFTj8uibh50",
#                     "id": "UgxgEFI5QddEkFem21t4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "اكس",
#                         "textOriginal": "اكس",
#                         "authorDisplayName": "Lana Khalil",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJX5Tbp3jWvpecl9ehkAxjOcQJ1z2LJ09OecbTt4Xg=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCPXS1HMYKtVcsj5TwxKvBEA",
#                         "authorChannelId": {"value": "UCPXS1HMYKtVcsj5TwxKvBEA"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-01-07T21:49:53Z",
#                         "updatedAt": "2022-01-07T21:49:53Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "g6_fXAZOR9452DQ2s4KNLPj40p8",
#             "id": "UgwnWDIGNr1Yx7lI5el4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "hepVVE1KoBSC_kphVddH0eLEzFQ",
#                     "id": "UgwnWDIGNr1Yx7lI5el4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "God bless you profesor!",
#                         "textOriginal": "God bless you profesor!",
#                         "authorDisplayName": "Mahmoud",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJU9mxrE809FjDzau-LtjwF1dKMGOjxCFn-wcSKmgg=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCdMSMP2iiRUjrsPy6_WjIzA",
#                         "authorChannelId": {"value": "UCdMSMP2iiRUjrsPy6_WjIzA"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2022-01-06T11:57:09Z",
#                         "updatedAt": "2022-01-06T11:57:09Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "GjbdHZXhCT4IaNNnwLlvV43tQUw",
#             "id": "UgwBNpAyBjGvjOgWUah4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "UWiHL9bJrxF5dAtDPXD7qr47tTI",
#                     "id": "UgwBNpAyBjGvjOgWUah4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "&quot;I shouldn&#39;t do this, but I will&quot;",
#                         "textOriginal": '"I shouldn\'t do this, but I will"',
#                         "authorDisplayName": "ABD",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJVXXphmogxU9vMMrH0NuTsJ_xoQNzBt4Kuxrk-CJxk=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UC5OX0kddu5bCsg4Ah3yWn5g",
#                         "authorChannelId": {"value": "UC5OX0kddu5bCsg4Ah3yWn5g"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 1,
#                         "publishedAt": "2021-12-17T16:35:07Z",
#                         "updatedAt": "2021-12-17T16:35:07Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#         {
#             "kind": "youtube#commentThread",
#             "etag": "Nbn9zwrJrAxoPzSMeCcLn28L16Q",
#             "id": "UgwL3Tv-24W-5Xzus2x4AaABAg",
#             "snippet": {
#                 "videoId": "YzZUIYRCE38",
#                 "topLevelComment": {
#                     "kind": "youtube#comment",
#                     "etag": "1zAhtlzIzoWDHi2ExfKhGxhJm7o",
#                     "id": "UgwL3Tv-24W-5Xzus2x4AaABAg",
#                     "snippet": {
#                         "videoId": "YzZUIYRCE38",
#                         "textDisplay": "Ax=b, then AtAx=Atb. awesome!",
#                         "textOriginal": "Ax=b, then AtAx=Atb. awesome!",
#                         "authorDisplayName": "Nion Cao",
#                         "authorProfileImageUrl": "https://yt3.ggpht.com/ytc/AL5GRJUMOE7ikP1DJYZp2GXQ5Gd_eCGPpyM1Y02HfSuZzQ=s48-c-k-c0x00ffffff-no-rj",
#                         "authorChannelUrl": "http://www.youtube.com/channel/UCDUFIAKR3YKe2EglNJulErQ",
#                         "authorChannelId": {"value": "UCDUFIAKR3YKe2EglNJulErQ"},
#                         "canRate": True,
#                         "viewerRating": "none",
#                         "likeCount": 0,
#                         "publishedAt": "2021-12-13T04:41:42Z",
#                         "updatedAt": "2021-12-13T04:41:42Z",
#                     },
#                 },
#                 "canReply": True,
#                 "totalReplyCount": 0,
#                 "isPublic": True,
#             },
#         },
#     ],
# }
